#!/usr/bin/env bash
rm -rf log
mkdir log

rm -rf ../data/graph
mkdir ../data/graph

rm -rf ../data/edges
rm -rf ../data/nodes

rm -rf ../data/tables
mkdir ../data/tables
rm -rf ../data/tmp
mkdir ../data/tmp
source env/bin/activate
python -m src
deactivate
